# AddGpsDevice.srv

# Request:
# The name of the device being added
string device_name

# The EUI64 identifier of the device from the lora_msgs package
lora_msgs/EUI64 device_eui

# The GPS coordinates and related data (latitude, longitude, altitude, etc.) from the sensor_msgs/NavSatFix message
sensor_msgs/NavSatFix nav_value

# True if device change localization False if not
bool is_moving
---
# Response:
# Indicates whether the device was successfully added (true for success, false for failure)
bool success

# Error message in case of failure, providing details about what went wrong
string error