#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# CreateDataBase.srv

# The key expression, e.g., "demo/example/**"
string key_expr

# The storage_name, e.g., "influxdb"
string storage_name

# The name of the database, e.g., "zenoh_example"
string db_name   

# Whether to create the database if it doesn't exist
bool create_db    
---
# Indicates if the operation was successful
bool success

# Response or message containing the result of the operation
string message    