#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# InfluxGetCurrentlyPlayingTopics.srv

# Request - empty (no parameters needed)
---
# Response
string[] topics           # List of topics currently being played back
string[] bucket_names     # Corresponding bucket names for each topic
string[] record_ids       # Corresponding record IDs for each topic
bool success              # Whether the operation was successful
string error_message      # Error message if success is false