#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# InfluxStopPlayingTopics.srv

# Request
string[] topics_names     # List of topic names to stop playing
---
# Response
bool success              # Whether the operation was successful
string error_message      # Error message (empty if successful, contains info about missing topics if partial success)