#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# AddSensorResponse.msg

# Unique identifier for a sensor.
# Example: "101"
int64 id

# Connection status of the sensor (true if connected, false otherwise).
# Example: "true"
bool connection