#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# EUI64.msg

# 64-bit Extended Unique Identifier (EUI-64).
# Example: "[0x00, 0x1A, 0x11, 0xFF, 0xFE, 0x12, 0x34, 0x56]"
uint8[8] data
