#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# MicroPublisherExtended.msg

# MicroPublisher message containing MicroPublisher.msg data.
MicroPublisher simple_micro_publisher_data

# NavSatFix message from the sensor_msgs package.
sensor_msgs/NavSatFix nav_value