#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

float32 battery_level # voltage
bool open
uint8 mod
uint32 total_door_open
uint32 last_door_open_duration # seconds
bool alarm_triggered
