#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# AddSensor.srv

# Unique identifier for a sensor or component.
# Example: "123456789"
int64 id

# Name of the sensor or component.
# Example: "Temperature Sensor"
string name

# Quality of Service settings for the topic communication.
# Example: "Reliable"
string qos

# Frequency of sensor updates or data transmission in Hz.
# Example: "10"
int64 frequency
---
# Unique identifier for a sensor or component.
# Example: "123456789"
int64 id

# Connection status (true if the sensor or component is connected, false otherwise).
# Example: "true"
bool connection