# AutomaticActionConnection.srv

string[] listen_topics        # An array of topic names that will be monitored. 
                              # Example: ["/topic1", "/topic2", "/topic3"]

string logic_expression       # A logical expression that combines the states of the monitored topics. 
                              # Example: "/topic1 and /topic2 or /topic3"

string pub_topic              # The name of the topic where a message will be published if the logic expression evaluates to true.
                              # Example: "/combined_action"

---
bool success                  # The result of the service execution: true if the operation was successful, false otherwise.