# AutomaticAction.srv

string listen_topic            # The name of the topic that will be monitored.
                               # Example: "/sensor_data"
   
string listen_message_type     # The type of ROS message expected on the topic.
                               # Example: "std_msgs/String"
   
string value                   # The name of the field within the message to be evaluated.
                               # Example: "data"
   
string trigger_val             # The threshold value against which the field is compared.
                               # Example: "100.0"
   
string trigger_type            # The type of comparison to be used. Possible values: "LessThan", "GreaterThan", "EqualTo".
                               # Example: "LessThan"
   
string pub_topic               # The name of the topic where the message will be published if the trigger condition is met.
                               # Example: "/triggered_action"
   
string pub_message_type        # The type of ROS message that will be published on the pub_topic. Not in use
                               # Example: "std_msgs/String"
   
string trigger_text            # The text content that will be published to the pub_topic.
                               # Example: "Action triggered!"
   
int64 data_validity_ms         # The validity period for the data in milliseconds.
                               # Example: "1000"
---
bool success                   # The result of the service execution: true if successful, false otherwise.