#
#  Copyright (C) 2025 wisevision
#
#  SPDX-License-Identifier: MPL-2.0
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# AutomaticActionCombinedDelete.srv

# The name of the combined topics publisher that is to be deleted.
# Example: "combined_publisher_1"
string name_of_combined_topics_publisher
---
# The result of the service execution: true if the deletion was successful, false otherwise.
# Example: "true"
bool success

# Message with error communicate.
# Example: "No such publisher found."
string error_message