name: Build and run ROS2 tests

on:
  pull_request:
    branches:
      - dev
      - main
      - 'stabilization/**'

jobs:
  build:

    runs-on: wisevision-runner

    continue-on-error: true

    container:
      image: ros:humble-ros-base

    steps:
    - name: Create workspace directory
      run: |
        mkdir -p wisevision_msgs_ws/src
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: wisevision_msgs_ws/src

    - name: Install dependencies
      run: |
            apt-get update
            rosdep update
            cd wisevision_msgs_ws
            rosdep install --from-paths src -i -y --rosdistro humble
    
    - name: Build test
      run: |
            . /opt/ros/humble/setup.sh
            cd wisevision_msgs_ws
            colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
      
    - name: Clean up workspace
      if: always()
      run: |
        sudo rm -rf wisevision_msgs_ws
